name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.5.1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build the Docker image
      uses: docker/bake-action@v1.5.0
      with:
        targets: linux/amd64,linux/arm64,linux/arm
        push: true
