name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.5.1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: chigusa/ddns:master
